#!/usr/bin/env bash
# Package a built cutemarkdown.exe into the two release artifacts:
#   <out>/cutemarkdown-<ver>-setup-x64.exe      NSIS installer (per-user, no admin)
#   <out>/cutemarkdown-<ver>-portable-x64.zip   cutemarkdown.exe + README.txt
#
# This is the single place that knows how to invoke makensis. It is used by
# scripts/build-windows.sh (Linux cross build) and by the GitHub workflows (Windows, Git Bash).
#
#   scripts/package.sh --exe path/to/cutemarkdown.exe [--version 1.2.3] [--out dist]
#
# Needs: makensis (NSIS 3) and Python 3. On Windows: `choco install nsis -y`.
#
# makensis gets no paths and no version on its command line. Under Git Bash they pass through MSYS
# argument conversion, and Windows tools add "\r" to anything they print. Instead the values are
# validated and written to installer/build-defs.nsh, which installer/cutemarkdown.nsi includes.
set -euo pipefail
# shellcheck source=scripts/_common.sh
. "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

EXE="" VERSION="" OUT="$ROOT/dist"
STAGE=""
DEFS="$ROOT/installer/build-defs.nsh"
cleanup() { rm -f "$DEFS"; if [ -n "$STAGE" ]; then rm -rf "$STAGE"; fi; }
trap cleanup EXIT
while [ $# -gt 0 ]; do
  case "$1" in
    --exe)     EXE=$2; shift 2 ;;
    --version) VERSION=$2; shift 2 ;;
    --out)     OUT=$2; shift 2 ;;
    -h|--help) sed -n '2,/^[^#]/{/^#/s/^# \{0,1\}//p;}' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$EXE" ] || { echo "error: --exe is required" >&2; exit 2; }
[ -f "$EXE" ] || { echo "error: $EXE does not exist (build it first)" >&2; exit 1; }
[ -n "$PY" ] || { echo "error: python3 not found" >&2; exit 1; }
[ -n "$VERSION" ] || VERSION=$("$ROOT/scripts/version.sh")
VERSION=$(strip_cr "$VERSION")
check_version "$VERSION"

# makensis: PATH first, then the default NSIS install locations on Windows.
MAKENSIS=$(command -v makensis || true)
if [ -z "$MAKENSIS" ]; then
  for c in "/c/Program Files (x86)/NSIS/makensis.exe" "/c/Program Files/NSIS/makensis.exe"; do
    if [ -x "$c" ]; then MAKENSIS=$c; break; fi
  done
fi
[ -n "$MAKENSIS" ] || { echo "error: makensis not found (Linux: apt install nsis, Windows: choco install nsis -y)" >&2; exit 1; }

mkdir -p "$OUT"
OUT=$(cd "$OUT" && pwd)
SETUP="$OUT/cutemarkdown-$VERSION-setup-x64.exe"
ZIP="$OUT/cutemarkdown-$VERSION-portable-x64.zip"
rm -f "$SETUP" "$ZIP"

MAKENSIS_VERSION=$(strip_cr "$("$MAKENSIS" -VERSION 2>/dev/null || true)")
echo "==> Installer (makensis ${MAKENSIS_VERSION:-?})"

# Build parameters for the installer script, as an include file (UTF-8 with BOM, so that makensis.exe
# does not read a non-ASCII user name in a path as ANSI). Paths are absolute and in the native form (C:\x\y on Windows).
printf '\357\273\277; Generated by scripts/package.sh for one build. Do not edit or commit.\n' > "$DEFS"
nsis_define() {   # NAME VALUE -> !define NAME "VALUE", refusing characters NSIS cannot take in a string
  local v=$2
  [ -n "$v" ] || { echo "error: $1 is empty" >&2; exit 1; }
  case $v in
    *'"'* | *$'\r'* | *$'\n'*) echo "error: $1 contains a quote or a line break: [$(printf '%s' "$v" | cat -v)]" >&2; exit 1 ;;
  esac
  printf '    %-9s [%s]\n' "$1" "$v"
  printf '!define %s "%s"\n' "$1" "$v" >> "$DEFS"   # File and OutFile take the text literally: no "$" escaping
}
nsis_define VERSION  "$VERSION"
nsis_define EXE_PATH "$(native "$EXE")"
nsis_define OUTFILE  "$(native "$SETUP")"

# Run from the installer directory so the script is named without a path (makensis would change
# into that directory anyway: the script's relative paths are resolved there).
(cd "$ROOT/installer" && MSYS2_ARG_CONV_EXCL='*' MSYS_NO_PATHCONV=1 "$MAKENSIS" -V2 cutemarkdown.nsi)
[ -f "$SETUP" ] || { echo "error: makensis finished but $SETUP was not created" >&2; exit 1; }

echo "==> Portable zip"
STAGE=$(mktemp -d)
cp "$EXE" "$STAGE/cutemarkdown.exe"
# CRLF line endings for Notepad. Drop any "\r" first: a checkout with autocrlf has them already.
sed "s/\r\$//; s/@VERSION@/$VERSION/g; s/\$/\r/" "$ROOT/installer/portable-README.txt" > "$STAGE/README.txt"
"$PY" - "$(native "$ZIP")" "$(native "$STAGE/cutemarkdown.exe")" "$(native "$STAGE/README.txt")" <<'PYEOF'
import os, sys, zipfile
out, *files = sys.argv[1:]
with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
    for f in files:
        z.write(f, os.path.basename(f))
PYEOF

echo "==> Done"
report "$SETUP" "$ZIP"
